name: Backend CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  backend-ci-cd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/microservices
          git pull origin master
          chmod +x build.sh
          ./build.sh
          docker compose stop
          docker compose rm -f
          docker compose build --no-cache
          docker compose up -d
